name: ride_hailer
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^4.4.1
  provider: ^6.0.3
  persistent_bottom_nav_bar: ^4.0.2
  pin_code_fields: ^7.4.0
  http: ^0.13.5
  geolocator: ^9.0.1
  flutter_svg: ^1.1.5
  mapmyindia_gl: ^0.2.2
  flutter_neumorphic: ^3.2.0
  modal_bottom_sheet: ^2.1.2
  geocoding: ^2.0.5
  shared_preferences: ^2.0.15
  socket_io_client: ^2.0.0
 
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.9
   

flutter:
  uses-material-design: true
  assets:
    - asset/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/icons/taxi.png"  
